### ISSUE TITLE
xunit - Закрытие открытых клиентов тестирования

### ISSUE THREAD

**Issue by artbear** [vanessa-opensource/add#128]
Режим xUnit сейчас не закрывает открытые клиенты тестирования.
Нужно добавить закрытие аналогично BDD

```
По умолчанию Vanessa Behavior не закрывает открытые клиенты тестирования. Для указания необходимости закрытия служит флаг ЗакрытьTestClientПослеЗапускаСценариев. Значение этого флага можно сразу установить в true.
```

@pumbaEO В незакрытии клиента тестирования может быть причина того, что файл 1cv8.1cd залочен во время сборки и сборка завершается с ошибкой

@VladFrost Напомни - для тест-клиентов xUnitFor1C через дымовой тест с помощью тест-клиентов мы сделали закрытие открытых сеансов тест-клиентов или нет?

**Comment by VladFrost** [comment]
> для тест-клиентов xUnitFor1C через дымовой тест с помощью тест-клиентов мы сделали закрытие открытых сеансов тест-клиентов или нет?

Нет, такого нет.
Если планируете делать, то делайте, пожалуйста, такое опционально.
Вообще, у меня Jenkins все запущенные в стадии процесс прибивает по окончании стадии, поэтому трудностей с незакрытием тест-клиентов я не испытваю.
А даже наоборот, часто испытываю трудности, когда тест-клиент закрывается раньше, чем все операции и отложенные записи отработали. Поэтому приходится в тестовых сценариях предусматривать паузу, чтобы тест-клиент не закрывался преждевременно.

**Comment by artbear** [comment]
@VladFrost Реализовано безусловное завершение 

Настройку не сделал (

https://github.com/vanessa-opensource/add/pull/782 уже в ветке девелоп.

Сможешь добавить настройку этого параметра, как ты выше писал?

**Comment by artbear** [comment]
Выполнено.
