### ISSUE TITLE
full localization

### ISSUE THREAD

**Issue by ghost** [vanessa-opensource/add#149]
полная локализация

* библиотечные шаги и описание
* генерируемые обработки - сниппеты
* интерфейс обработок

нужно еще проверить где нужно

**Comment by allustin** [comment]
заметки варианты

* crowdin
* zanata
* weblate

p.s. нужно официально опубликовать помощник перевода на базе xslt в хабе пакетов

**Comment by pbazeliuk** [comment]
Необходима локализация на языки:
- Украинский (uk)
- Английский (en)
- Английский канадский (en_CA)

В рамках этой задачи, могу локализировать, те части которые наиболее часто использую?

**Comment by artbear** [comment]
Да, помощь была бы очень полезна!

**Comment by artbear** [comment]
неактуально.
