### ISSUE TITLE
BDDRunner: Генерация ИменЛокализованногоAPIПроцедур

### ISSUE THREAD

**Issue by ghost** [vanessa-opensource/add#206]
Контекст

* допустим я кодирую на Украинском, обычно в этом случае я работаю и кодирую на Украинском, а вот ключевые слова могу использовать как английские, так и русские.

У нас 3 сценария

* генерация обработок (шагов проверки поведения)
* перегенерация обработок
* использование библиотечных шагов

и матрица локализации

* ключевые слова - английские, русские
* имена шагов/сценариев - любые

Отсюда возникает желание

* сделать ГенераторEPF полноценным плагином
* сделать возможность выбора настроек - какие ключевые слова использовать при генерации Русские/Английские
* понять как перегенировать процедуры, если при перегенрации меняется лвариант локализации

Связано с большим эпиком - полная локализация

**Comment by artbear** [comment]
Неактуально.
