### ISSUE TITLE
Отсутствует перевод части библиотечных шагов на английский язык

### ISSUE THREAD

**Issue by seramiti** [vanessa-opensource/add#310]
**Проблема:** отсутствует перевод некоторых библиотечных шагов на английский

**Шаги по которым нет перевода:**
в базе   нет элементов Справочника "%1 Справочник1"
В базе   появился хотя бы один элемент справочника "%1 Справочник1"
в   метаданных есть Справочник "%1 Справочник1"
Дано   установлен OneScript
Дано:   Имеется метаданное "%1 Справочник.Справочник1"
Допустим   адрес ящика '%1 0.0.0.0'
Допустим   период опроса почты '%1 1' сек
Допустим   порт ящика '%1 1080'
Если в   таблице "%1 ИмяТаблицы" поле с именем "%2 ИмяПоля" имеет   значение "%3 ЗначениеПоля" тогда
Если   текущее окно имеет заголовок "%1 ИмяОкна" Тогда
Затем я   загружаю базу "%1 СтрокаСоединенияСБазой" из DT "%2   ПутьКDT"
Затем я   создаю пустую базу "%1 ПараметрыСозданияБазы"
И в   базе есть элементы справочника "%1 Справочник1" с указанными в   таблице наименованиями
И в   базе нет записей РегистрСведений "%1 РегистрСведений1"
И в базе   нет элементов справочника "%1 Справочник1" с указанными в таблице   наименованиями
И в   таблице "%1 ИмяТаблицы" в поле '%2 Заголовок поля' я ввожу значение   выражения "%3 Выражение"
И в   таблице "%1 ИмяТаблицы" в поле с именем '%2 ИмяПоля' я ввожу   значение выражения "%3 Выражение"
И в   таблице "%1 ИмяТаблицы" я перехожу к строке по шаблону      \|'Наименование'\|      \|'*ЧастьСтроки*'\|
И в   таблице "%1 ИмяТаблицы" я снимаю флаг с именем "%2   ИмяФлага"
И в   таблице "%1 ИмяТаблицы" я устанавливаю флаг с именем "%2   ИмяФлага"
И Код   возврата равен "%1 0"
И   письма для "%1 Получатель"
И   письма от "%1 Отправитель"
и   существует макет "%1 ТысячаЭлементовСправочника1"
И   текстом письма "%1 Текст"
И темой   письма "%1 Тема"
И я   вижу в консоли вывод "%1 ."
И Я   загружаю макет "%1 Макет" и сохраняю данные из макета в переменную   "%2 ДанныеИзМакета"
И я   загружаю макет "%1 ТысячаЭлементовСправочника1"
И Я   создаю элементы справочника "%1 Справочник1" с указанными в таблице   наименованиями
И я   удаляю все записи РегистрСведений "%1 РегистрСведений1"
И я   фиксирую текущую форму
Когда в   метаданных есть РегистрСведений "%1 РегистрСведений1"
Когда Я   выполняю команду "%1 oscript" с параметрами "%2 -version"
Когда Я   задаю параметры считывания макета НачСтр "%1 1" НачКол "%2   1" КолСтр "%3 100" КолКол "%4 20"
Когда Я   задаю системные параметры считывания макета НачСтр "%1 1" НачКол   "%2 1" КолСтр "%3 100" КолКол "%4 20"
Когда   Я копирую текущий профиль TestClient с установкой параметров:      \| 'Имя подключения' \| 'Синоним' \|   'Порт' \| 'Строка соединения' \| 'Логин' \| 'Пароль' \| 'Запускаемая обработка' \|   'Дополнительные параметры строки запуска' \|      \| 'ИмяПрофиля' \| 'СинонимПрофиля' \|   '1538' \| 'Srvr="localhost:1941";Ref="Test";' \| 'Админ' \|   'Админ' \| 'c:\СуперОбработка.epf' \| '/UC' \|
Тогда В   базе появилась хотя бы одна запись РегистрСведений "%1   РегистрСведений1"
Тогда В   списке элементов справочника "%1 Справочник1" существует не менее   "%2 1000" элементов
Тогда в   ящике есть новые письма
Тогда в   ящике есть письма
Тогда в   ящике есть письма для "%1 Получатель"
Тогда в   ящике есть письма от "%1 Отправитель"
Тогда в   ящике есть письма с текстом "%1 Текст"
Тогда в   ящике есть письма с темой "%1 Тема"
Тогда   очищаем ящик от писем
Тогда Я   сообщаю вывод команды "%1 oscript"
я   создаю сам один элемент справочника "%1 Справочник1"
я удаляю   все элементы Справочника "%1 Справочник1"

 - Редакция 1С платформы 8.3.12.1595
 - Версия VB 5.5.5
 - Версия OScript 1.0.20.108

**Comment by artbear** [comment]
@seramiti Да, есть такая проблема с новыми шагами.

Планируем заняться и этой проблемой.

Постепенно закрываем все технические долги.

**Comment by artbear** [comment]
Проект в активной разработке, так что и этот тех.долг скоро исправим.

**Comment by artbear** [comment]
@seramiti И большущее спасибо за столь полный список проблем перевода.

**Comment by artbear** [comment]
К сожалению, стало неактульно. закрываю.
