### ISSUE TITLE
Генератор стандартного конфига для дымового тестирования на основании данных о поддержке

### ISSUE THREAD

**Issue by thedemoncat** [vanessa-opensource/add#373]
**Генератор стандартного конфига для дымового тестирования**

```gherkin
Допустим есть типовая конфигурация на поддержке, например ERP, 
И у нее есть определенное количество форм которые с коробки не открываются
И есть файл "ParentConfigurations.bin" в котором хранятся текущее состояние поддержки объектов. 

Сценарий:
Когда я открываю инструмент генератор настроек дымового тестирования на чистой базе
И нажимаю кнопку "Создать шаблонный файл"
То происходит разбор файла "ParentConfigurations.bin" 
И в исключения конфига овтоматически добавляются объекты заблокированные от изменений
```

Это упростит формирование конфига при начальной имплементации TDD тестирования

`ParentConfigurations.bin` - по факту текстовый файл с расширением bin

**Comment by abirambul** [comment]
На ИТС есть обработка АвтоформатированиеКодаИЛокализация.epf.

Там есть разбор файла `ParentConfigurations.bin`

Может пригодится.

**Comment by artbear** [comment]
@abirambul Большое спасибо, полезная ссылка.

**Comment by artbear** [comment]
Я сделал спец.инструмент vanessa-support - приложение на 1скрипт

с его помощью легко сгенерить файл настройки в нужном формате.
и легко подключить.

примеры есть в коммите https://github.com/vanessa-opensource/add/commit/b98b0aee10e92e0665fda491cb3738ad332d6346

описание инструмента https://github.com/vanessa-opensource/vanessa-support

**Comment by artbear** [comment]
т.е. теперь можно автоматически использвать актуальный файл с настройками поддержки.

и анализировать, например, 
- на 1 этапе тестирования - только изменяемые метаданные
- а на следующих все остальные метаданные

**Comment by artbear** [comment]
также расширены настройки подключения\исключения метаданных в https://github.com/vanessa-opensource/add/pull/900

**Comment by artbear** [comment]
Выполнено.
