### ISSUE TITLE
УФ: Ошибка, когда в загружаемой обработке тестов нет, при попытке выполнить тесты

### ISSUE THREAD

**Issue by pbazeliuk** [vanessa-opensource/add#382]
**Описание ошибки**
Если загрузить дымовой тест и не будет добавлено тестов в менеджер тестирования. При попытке выполнить тесты получим ошибку:

```1c-enterprise
{ExternalDataProcessor.xddTestRunner.Form.УправляемаяФорма.Form(571)}: Value is not of object type (Состояние)
	УзелДереваТестов.Состояние = РезультатТестирования.Состояние;
```

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть в управляемом режиме xddTestRunner
2. Загрузить дымовой тест 'тесты_ПроверкаМакетовСКД.epf'
3. В конфигурации не должно быть макетов СКД
3. Нажать кнопку 'Выполнить все тесты' или 'Выполнить выделенные тесты'
4. Получим ошибку 

**Ожидаемое поведение если бы ошибки не было**
Ошибки нет

**Скриншоты**
![image](https://user-images.githubusercontent.com/8529755/51250304-a5480b00-199e-11e9-9499-1113b64d946d.png)

**Окружение:**
 - Версия операционной системы: Windows 8.1
 - Редакция 1С платформы: 8.3.12.1567
 - Версия ADD: 5.6.0
 - Версия OScript: 1.0.21.1

**Comment by pbazeliuk** [comment]
Предлагаю внести изменения в код, строке: 671 `{ExternalDataProcessor.xddTestRunner.Form.УправляемаяФорма.Form(671)}`

```1c-enterprise
	Если РезультатТестирования.Строки.Количество() = 0 Тогда
		РезультатТестирования = Неопределено;
	Иначе
```

на 

```1c-enterprise
	Если РезультатТестирования.Строки.Количество() > 0 Тогда
		...
	КонецЕсли;
```
Так как результат выполнения тестов `Неопределено` дальнейшая обработка параметра приводит к ошибке.

**Comment by maximsamokhval** [comment]
@artbear могу взять в работу, но то, что ты пишешь по поводу проверки на Неопределено , то не везде есть проверки.

Например, метод ВыполнитьТестыНаКлиенте (строка 157) , внутри которого 
есть вызов, который не проверяет на Неопределено.

Как и где лучше внести изменения?

``` bsl
РезультатыТестирования = ВыполнитьТесты(Плагин(ИдентификаторЗагрузчика), ЭтаФорма.ДеревоОтЗагрузчика, Фильтр, ЭтаФорма);

ОбновитьДеревоТестовНаОснованииРезультатовТестирования(ДеревоТестов.ПолучитьЭлементы()[0], РезультатыТестирования);
```

![image](https://user-images.githubusercontent.com/24194977/141983845-d1b4f62e-938d-4479-bbb9-927275261930.png)

**Comment by artbear** [comment]
@maximsamokhval ну да. я про это и пишу, что не везде есть проверки после ВыполнитьТесты и нужно аккуратно добавить проверки на `Если Не ЗначениеЗаполнено(РезультатыТестирования) Тогда`

где-то с возвратом из метода, где-то с обходом
