### ISSUE TITLE
Не передается пароль в клиент тестирования

### ISSUE THREAD

**Issue by komarovps** [vanessa-opensource/add#422]
**Описание ошибки**
При запуске дымовых тестов с параметром `ОткрываемФормыНаКлиентеТестирования` через vanessa-runner в клиент тестирования не передается пароль указанный в параметре `--db-wpd`

**Сценарий воспроизведения**
Запустить дымовые тесты через vanessa-runner - `vrunner xunit --settings ./vRunner.json`
Менеджер тестирования запускается с логином (`--db-user`) и паролем (`--db-pwd`) указанными в файле настроек vRunner.json 
Далее происходит запуск клиента тестирования, который останавливается на окне ввода логина и пароля. 

**Ожидаемое поведение, если бы ошибки не было**
Клиент тестирования запустился с паролем переданным для менеджера тестирования через параметр `--db-pwd`

**Окружение:**

 - Редакция платформы 1С [`8.3.12`]
 - Версия `Vanessa.ADD` [`5.7.0`]

**Дополнительный контекст**

- Пароль в клиент тестирования можно передать через параметр vrunner `--testclient`

**Comment by artbear** [comment]
@komarovps Спасибо за то, что ишуз все-таки создал :)

**Comment by artbear** [comment]
@komarovps Может быть, есть смысл доработать ванесса-раннер, чтобы он передавал правильно заполненный `--testclient` 
- при запуске дымовых тестов через `vrunner xunit` 
- отсутствии явно заданной опции `--testclient`
- и указании `--db-pwd`

@komarovps @pumbaEO что скажете?

**Comment by artbear** [comment]
@VladFrost твое мнение по этому вопросу также интересно.

**Comment by VladFrost** [comment]
Сейчас `add` понимает, что ему надо запустить клиенты тестирования, когда ему передан параметр `xddTestClient`. В `vanessa-runner` это происходит здесь:
https://github.com/silverbulleters/vanessa-runner/blob/develop/src/Классы/КомандаТестирование_xUnitFor1C.os#L208 

Т.ч. если надо указать конкретные реквизиты, то необходимо и достаточно запускать `vrunner` с параметром `--testclient`.

Ну или можно, конечно, заморочиться, и организовать параметризацию и механику подключения тест-клиентов здесь: https://github.com/silverbulleters/add/blob/master/tests/smoke/тесты_ОткрытиеФормКонфигурации/Тесты_ОткрытиеФормКонфигурации/Forms/УправляемаяФорма/Ext/Form/Module.bsl#L33 

Т.е. указывать не только параметр `ОткрываемФормыНаКлиентеТестирования`, но и параметры подключения клиентов тестирования и передавать их в функцию `ПодключитьТестКлиент()` https://github.com/silverbulleters/add/blob/master/plugins/ТестКлиенты/ТестКлиенты/Forms/Форма/Ext/Form/Module.bsl#L74 

PS: Имя параметра имхо неудачно выбрали. Есть рекомендация образовывать от неопределенной формы глагола, т.е. `ОткрыватьФормыНаКлиентеТестирования`.

**Comment by artbear** [comment]
Еще комментарий из телеграма

>сработало, но только когда testclient последним параметром поставил. спасибо большущее!

**Comment by Ojgenby** [comment]
Добрый день. Подскажите пожалуйста, что должны передавать в параметре testclient?

**Comment by artbear** [comment]
уже сделано ранее
