### ISSUE TITLE
Настройки не сохраняются при закрытии формы xddtestrunner, из-за не корректного определения ПакетногоЗапуска

### ISSUE THREAD

**Issue by mity1982** [vanessa-opensource/add#439]
### Предварительно

*Я использую версию - "5.8.0.0"
* я проверил issues
* копия issue в проекте xddtestrunner - #791
* код в сообщении из  xddtestrunner "4.2.0.0", но я проверил, в текущем релизе add, тоже самое

## Описание

Не сохраняются настройки при закрытии управляемой формы браузера тестов.

**Шаги для воспроизведения**

1. Запустить предприятие из конфигуратора в режиме /РежимОтладки
2. Загрузить тесты от куда угодно которых нет в истории загрузки
3. Выйти из браузера

**Ожидаемое поведение:** При повторном входе путь к загруженным теста должен быть в истории загрузки

**Текущее поведение:** В истории загрузки нет ранее загруженного теста

**Укажите:**
* "4.2.0.0"
* 8.3.9
* /РежимОтладки

## Также приветствуется описание в формате Gherkin

```Gherkin
Функционал <Необходимый эффект>
   Как программист
   Я хочу чтобы была история загрузки тестов

Контекст
  Дано 4.2.0.0
  И 8.3.8
  и /РежимОтладки

Сценарий 
  Допустим открыл тесты в браузере тестов и закрыл браузер и режим запуска "/РежимОтладки"
  Когда открываю браузер тестов повторно
  Тогда в истории есть путь к тестам которые открывал в прошлый раз

```
При открытии браузера тестов устанавливается:
`ЭтоПакетныйЗапуск = ЗначениеЗаполнено(ПараметрЗапуска ** = "/РежимОтладки");`
(устанавливается Истина, хотя это не пакетный запуск, что бы ни значило "Пакетный")
При закрытии браузера тестов:

```
&НаКлиенте
Процедура ПриЗакрытии()
	
	// Для пакетного запуска нет смысла вызывать это событие,
	Если НЕ ЭтоПакетныйЗапуск Тогда
		ПриЗакрытииНаСервере();
	КонецЕсли;
	
КонецПроцедуры

&НаСервере
Процедура ПриЗакрытииНаСервере()
	ЭтотОбъектНаСервере().СохранитьНастройки();
КонецПроцедуры
```

сохранение настроек не происходит

///

я быстро поправил на 

`ЭтоПакетныйЗапуск = ЗначениеЗаполнено(ПараметрЗапуска) И ПараметрЗапуска <> "/РежимОтладки";`

но правильней, конкретно указать критерии пакетного запуска в строке РежимЗапуска

**Comment by Ndochp** [comment]
@artbear в версии 6.5.0 не то что история не сохраняется, открытия не происходит. (точнее все закрывается при попытке выплонить пакетный режим)
В 6.7.0 просто ругается сообщением.
```
Ошибка загрузки и выполнения тестов в пакетном режиме
Vanessa-ADD: Я не знаю что мне делать. Нет приказа на выполнение тестов или закрытие.
```

Предлагаю замену 

``` bsl
	//ЭтоПакетныйЗапуск = ЗначениеЗаполнено(ПараметрЗапуска);
	ЭтоПакетныйЗапуск = СтрНайти(ПараметрЗапуска, "xdd") > 0;
```

Ну или если мы хотим оставить поведение Ванессы про "нет приказа" то сделать проверку на БСП параметры запуска и сначала выкидывать их, а потом если что-то еще осталось, то считать запуск пакетным.

**Comment by artbear** [comment]
@Ndochp мне также нравится вариант замены на 
`ЭтоПакетныйЗапуск = СтрНайти(ПараметрЗапуска, "xdd") > 0;`

самое простое и полезное

**Comment by artbear** [comment]
Выполнено.

исправлено на вариант `ЭтоПакетныйЗапуск = Найти(ПараметрЗапуска, "xdd") > 0;`

**Comment by artbear** [comment]
и для УФ, и для ОФ
