### ISSUE TITLE
Шаблоны поиска в конфигурационном файле xddTestRunner

### ISSUE THREAD

**Issue by ovcharenko-di** [vanessa-opensource/add#445]
**Существует проблема**
При настройке исключений в конфигурационном файле дымовых тестов необходимо указывать имя каждого исключаемого объекта метаданных по отдельности. Для больших конфигураций это может быть очень трудоемко.

**Хотелось бы иметь следующую функциональность**
Предоставить возможность указывать в конфигурационном файле **шаблон поиска** для имен объектов метаданных (например, "*ПрисоединенныеФайлы"), чтобы при запуске тестов xddTestRunner сам определял, какие объекты метаданных подходят под этот шаблон.

**Comment by ovcharenko-di** [comment]
@artbear, есть вопрос. Хочу использовать плагин "РегулярныеВыражения" в процедуре "ДобавитьТестыДляСправочниковСервер", но она &НаСервереБезКонтекста. Как используются плагины в других частях проекта в формах из серверных процедур?
Как лучше поступить?

**Comment by artbear** [comment]
>@artbear, есть вопрос. Хочу использовать плагин "РегулярныеВыражения" в процедуре "ДобавитьТестыДляСправочниковСервер", но она &НаСервереБезКонтекста. Как используются плагины в других частях проекта в формах из серверных процедур?
Как лучше поступить?

@ovcharenko-di пропустил твой вопрос (
ответ есть в https://github.com/silverbulleters/add/blob/master/F.A.Q.MD Вопрос №7

**Comment by artbear** [comment]
Важный комментарий о том, что уже есть реализация https://github.com/vanessa-opensource/add/pull/877#issuecomment-898858526
