### ISSUE TITLE
 xunit ПроверкаЧтенияНеАдминистраторами 

### ISSUE THREAD

**Issue by grahovsky** [vanessa-opensource/add#454]
**Существует проблема**
при запуске стандартных дымовых (add 5.8) через vrunner xunit,
ПроверкаЧтенияНеАдминистраторами - вызывает безусловный крашь в случае, если ролей в системе нет, либо есть объекты с правами только у Администраторов

**Хотелось бы иметь следующую функциональность**
возможность отключить проверку в стандартных дымовых через параметры файла xUnitParams.json
"ПроверкаЧтенияНеАдминистраторами": []
ИЛИ
"ПроверкаЧтенияНеАдминистраторами": false,

**Comment by artbear** [comment]
@grahovsky Да, новым дымовым тестам не хватает возможности отключения или настройки.

сделаем.

**Comment by artbear** [comment]
аналогичная тема в https://github.com/vanessa-opensource/add/issues/748

**Comment by artbear** [comment]
уже исправлено.
