### ISSUE TITLE
Добавление новых видов дымовых тестов (формы регистров сведений, накопления и т.д.)

### ISSUE THREAD

**Issue by ovcharenko-di** [vanessa-opensource/add#485]
**Хотелось бы иметь следующую функциональность**
В дымовых тестах по открытию форм не хватает тестов для форм регистров.

**Comment by artbear** [comment]
Да, уже можно добавить.

не очень часто нужны, но добавить несложно.

@ovcharenko-di Сможешь сам сделать?
например, по образу и подобию недавно добавленных бизнес-процессов?

**Comment by ovcharenko-di** [comment]
@artbear, смогу! Сделаю на досуге
