### ISSUE TITLE
Некорректное отображение текста ошибки при дымовом тестировании

### ISSUE THREAD

**Issue by lashmyash** [vanessa-opensource/add#603]
**Описание ошибки**

При формировании отчета по тестированию ОткрытиеФормКонфигурации, текст ошибки нечитаемый. Происходит после обновления платформы на 8.3.15

**Сценарий воспроизведения**
1. Запустить xddTestRunner - Тесты_ОткрытиеФормКонфигурации
2. Дойти до формы с модальным окном
3. Получить ошибку как на скриншоте

![image](https://user-images.githubusercontent.com/30473095/67945725-acb86800-fbf0-11e9-9ff6-e96a9a06d6fd.png)

**Ожидаемое поведение, если бы ошибки не было**
Текст ошибки старого вида:
```
[Failed] Выявлено модальное окно:
[Переход по кнопке командного интерфейса] Поле объекта не обнаружено (ОбъектМаршрута) 
	ВызватьИсключение Префикс + " " + СообщениеОшибки; 
```

**Окружение:**

```
 - Версия операционной системы: Windows 10 (64)
 - Редакция платформы 1С 8.3.15.1700
 - Версия Vanessa.ADD 6.4.0
 - Версия OneScript 1.1.1
```

**Comment by artbear** [comment]
@lashmyash В версии 8.3.15 наконец-то добавили стек вызова, приводящий к ошибке.

стало удобно изучать ошибки.

Соглашусь, что теперь текст в отчете тестирования стал менее читаем.

Думаю, как уменьшить список стека вызова, чтобы пользователю было удобнее.

**Comment by KrapivinAndrey** [comment]
@artbear Чтобы получить полный стек надо вызвать ПодробноеПредставлениеОшибки. Можно выводить обычное как строку, а подробное как аттач возможно. Посмотрю

**Comment by artbear** [comment]
@KrapivinAndrey смотрел эту проблему? как-то решал что-то подобное?

**Comment by KrapivinAndrey** [comment]
@artbear Ой. Вообще забыл про нее) надо к годовщине тогда пофиксить.

**Comment by KrapivinAndrey** [comment]
@artbear Отправил pr. Пока делал - появилась идея обрабатывать это описание ошибок и сворачивать. По аналогии с java или [pretty-errors](https://pypi.org/project/pretty-errors/)

**Comment by artbear** [comment]
Выполнено.
