### ISSUE TITLE
Дымовые тесты зависают на диалоге выбора файла windows

### ISSUE THREAD

**Issue by aleshko-dev** [vanessa-opensource/add#625]
**Описание ошибки**
Тесты зависают и не выполняются дальше когда появляется диалог выбора файла windows инициированный из 1C

**Окружение:**

 - Версия операционной системы: `Windows 10 (64)`
 - Редакция платформы 1С  `8.3.14.1694`
 - Версия `Vanessa.ADD` `6.4.0`
 - Версия `OneScript` `1.1.1`

**Дополнительный контекст**

- Типовая или не типовая конфигурация? `- Не типовая`
- Включен ли режим защиты от опасных действий? `- Нет`

**Comment by artbear** [comment]
@aleshko-dev управляемое приложение или обычное приложение?

**Comment by artbear** [comment]
@aleshko-dev если управляемое, используется запуск дымовых через тест-клиент или нет?

**Comment by artbear** [comment]
Сделано в https://github.com/vanessa-opensource/add/pull/753
