### ISSUE TITLE
Пауза через пинг 

### ISSUE THREAD

**Issue by KrapivinAndrey** [vanessa-opensource/add#675]
**Существует проблема**
Часто пауза в коде реализована через Пинг, и в логах это выглядит ужасно

**Хотелось бы иметь следующую функциональность**
Большое количество пауз можно реализовать через ПодключитьОбработчикОжидания

![image](https://user-images.githubusercontent.com/586025/74721031-92b29c00-5258-11ea-9651-afff74bce641.png)

**Comment by pumbaEO** [comment]
пауза через пинг синхронная, пауза вызываетса в некоторых шагах типа ждать завершения закрытия окна nсекунд.
Если перевести на асинхрон тогда такие реализации перестанут работать.
```
//Тогда я пропикиваю штрихкоды принятых товаров
//@ЯПропикиваюШтрихкодыПринятыхТоваров(ТабПарам)
Процедура ЯПропикиваюШтрихкодыПринятыхТоваров(ТабПарам) Экспорт
	//Ванесса.ПосмотретьЗначение(Парам01,Истина);
	//ВызватьИсключение "Не реализовано.";
	
	Таблица = ПреобразоватьТаблицуВМассивСтруктур(ТабПарам);
	Для каждого Строка из Таблица Цикл
		КоличествоРаз = Число(Строка.Количество);
		Штрихкод = Строка.Штрихкод;
		Ванесса.Шаг("Тогда открылось окно 'Проверка количества товаров в приходном ордере*'");
		Пока КоличествоРаз > 0 Цикл
			
			Ванесса.Шаг("И я нажимаю на кнопку 'Найти товар по штрихкоду'");
			Ванесса.Шаг("Тогда открылось окно 'Введите штрихкод'");
			Ванесса.Шаг(СтрШаблон("И в поле 'InputFld' я ввожу текст '%1'", Штрихкод));
			Ванесса.Шаг("И я нажимаю на кнопку 'OK'");
			КоличествоРаз = КоличествоРаз - 1;
		КонецЦикла;
	КонецЦикла;

КонецПроцедуры
```

**Comment by KrapivinAndrey** [comment]
Я не предлагаю совсем отказаться от паузы. но минимизировать ее.

Кажется, что(то что в основном валится в лог) пауза при поиске тестклиента может быть реализована через ПодключитьОбработчикОжидания

**Comment by zeratulayuris** [comment]
Можно вместо этого доработать и использовать сниппет отсюда: https://fastcode.im/templates/Details/6543

**Comment by artbear** [comment]
@KrapivinAndrey а может быть, просто убрать показ лога при выполнении этой команды?

на винде вроде нет проблем, а вот на линуксе такой спам, верно?

**Comment by pumbaEO** [comment]
Это особености 1с она и транслирует в стандартный вывод а мы стандартный вывод считываем oscript и дальше его пробрасываем

**Comment by KrapivinAndrey** [comment]
Кажется это не 1с. Это сборка на linux(точнее в докере). Там же нет "выполнить без показа черного окна". Поэтому и получаем в лог весь вывод

**Comment by artbear** [comment]
@KrapivinAndrey я выпустил релиз 6.6.0, а в нем  я скрываю вывод пинга через > dev/null

вроде бы должно прятать вывод в линуксе

проверишь?

**Comment by artbear** [comment]
@KrapivinAndrey подтвердил, что шума от пинга в линуксе больше нет. УРА!

сделано в 6.6.0
