### ISSUE TITLE
Путаниция контекстов smoke_CommonsModules в интерактивном режиме xddtestRunner

### ISSUE THREAD

**Issue by silverbulleters-github-service** [vanessa-opensource/add#722]

**Comment by artbear** [comment]
непонятно, что не так. поясни? @silverbulleters-github-service

**Comment by asosnoviy** [comment]
@artbear ты с ботом разговариваешь? 😕

**Comment by pbazeliuk** [comment]
Ага, это использую у себя в тестах, что там не так?

**Comment by artbear** [comment]
закрываю, т.к. нет ответа от автора.
