### ISSUE TITLE
Нет возможности указать дополнительные параметры запуска тест-клиента для дымовых

### ISSUE THREAD

**Issue by KrapivinAndrey** [vanessa-opensource/add#723]
**Существует проблема**
Смоук-тесты не дают указать дополнительные параметры. 

**Хотелось бы иметь следующую функциональность**
Добавить параметр xddAdditional для указания доппараметров клиента тестирования

**Дополнительный контекст**
Для снятие замеров

**Comment by artbear** [comment]
@KrapivinAndrey Расшифруй, чего не хватает.

json-файла настроек не хватает?

**Comment by KrapivinAndrey** [comment]
@artbear Возможно я просто не догнал.
ТестКлиент в дымовых подключается через плагин ТестКлиеты в пакетном режиме.
Как мне в него передать дополнительный параметр: 
/debug -http -attach /debuggerURL http://127.0.0.1:2550

**Comment by artbear** [comment]
Насколько я понимаю, такой возможности еще не сделано.

@VladFrost поправь меня, если я ошибаюсь.

**Comment by artbear** [comment]
Если такого нет, возможно расширить так
```
--testclient - Параметры подключения к тест-клиенту вида --testclient ИмяПользователя:Пароль:Порт:"Любые нужные параметры, передаваемые тест-клиенту"
Пример 1: --testclient Администратор:пароль:1538
Пример 2: --testclient ::1538 (клиент тестирования будет запущен с авторизацией от менеджера тестирования)
Пример 3: --testclient Администратор:пароль:1538:"/debug -http -attach /debuggerURL http://127.0.0.1:2550"
```

т.е. добавляем еще один суб-параметр к опции тест-клиент только в Ванесса-АДД и не придется менять ванесса-раннер.

@VladFrost @KrapivinAndrey что скажете?

**Comment by KrapivinAndrey** [comment]
Кажется проще добавить опцию --testclient-additional

**Comment by KrapivinAndrey** [comment]
Потому что строка разделится по : из http://

**Comment by VladFrost** [comment]
> json-файла настроек не хватает?

Мне тоже нравится идея с файлом с настройками. Там кроме параметров подключения отладчика можно было и ещё что-то указать. Например, параметры команды для записи скриншотов.

**Comment by KrapivinAndrey** [comment]
@VladFrost Есть же такой файл: xUnitParams. Другое дело что там параметров мало

**Comment by artbear** [comment]
Выполнено в https://github.com/vanessa-opensource/add/pull/754 и https://github.com/vanessa-opensource/vanessa-runner/pull/367
