### ISSUE TITLE
Из командной строки не грузятся дымовые тесты в 6.6.0 в 8.3.14

### ISSUE THREAD

**Issue by artbear** [vanessa-opensource/add#725]
**Описание ошибки**
```
vanessa-runner v1.10.0
ИНФОРМАЦИЯ - Выполняю тесты  с помощью фреймворка Vanessa-ADD (Vanessa Automation Driven Development) - D:\Tools\OneScript\lib\add\tests
ИНФОРМАЦИЯ - Выполняю команду/действие в режиме 1С:Предприятие
ИНФОРМАЦИЯ - vanessa-add ver. 6.6.0
ИНФОРМАЦИЯ - Ошибка загрузки и выполнения тестов в пакетном режиме
ИНФОРМАЦИЯ - Метод объекта не обнаружен (смв_ОписаниеОповещения)
ИНФОРМАЦИЯ - {ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1271)}:       ОбработкаОповещения = АСинк().смв_ОписаниеОповещения("ВыполнитьШагПакетногоЗапуска", ЭтаФорма, Состояние, "ВыполнитьШагПакетногоЗапускаИсключение", ЭтаФорма);
ИНФОРМАЦИЯ - {ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1264)}:       ВыполнитьШагПакетногоЗапуска(, Состояние);
ИНФОРМАЦИЯ - {ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(1168)}:                       ВыполнитьПакетныйЗапускАсинхронно(НастройкиШагов)
ИНФОРМАЦИЯ - {ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(68)}:         ВыполнитьПакетныйЗапуск(ПараметрЗапуска);
ИНФОРМАЦИЯ - {ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(350)}:        ПриОткрытииЗавершение();
ИНФОРМАЦИЯ - {ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(343)}:        ЗагрузкаПлагиновЗавершение();
ИНФОРМАЦИЯ - {ВнешняяОбработка.xddTestRunner.Форма.УправляемаяФорма.Форма(273)}:                ПодключитьНайденныеКлиентскиеПлагины(ПомещенныеФайлы, ИдентификаторыПлагинов);
ИНФОРМАЦИЯ - Выполнение команды/действия в режиме 1С:Предприятие завершено.
ОШИБКА - Причина ошибки:Получен неожиданный/неверный результат работы - Не найден файл статуса D:\Work\Repos\devops-infostart\build\xddExitCodePath.txt
Возможна, работа 1С:Предприятие завершилась некорректно.
КРИТИЧНАЯОШИБКА - {Модуль D:\Tools\OneScript\lib\vanessa-runner\src\Классы\МенеджерКонфигуратора.os / Ошибка в строке: 286 / Получен неожиданный/неверный результат работы - Не найден файл статуса D:\Work\Repos\devops-infostart\build\xddExitCodePath.txt
Возможна, работа 1С:Предприятие завершилась некорректно.}
```

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**
Alexander Kuzin, [04.05.20 14:01]
Техническая информация:
  - Версия Vanessa-ADD: 6.6.0
  - Имя конфигурации: БиблиотекаСтандартныхПодсистемДемо
  - Синоним конфигурации: Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1
  - Версия конфигурации: 3.1.2.366
  - Платформа 1С: 8.3.15.1943
  - Режим совместимости (для TestManager): Версия8_3_14
  - Режим совместимости интерфейса (для TestManager): ТаксиРазрешитьВерсия8_2
  - Режим запуска: Управляемое приложение (Тонкий клиент)
  - Тип базы: Файловая ИБ
  - Язык (для TestManager): Русский
  - Локализация (для TestManager): ru_RU
  - Операционная система: Windows x86-64 Microsoft Windows 10 version 10.0  (Build 18363)

**Comment by artbear** [comment]
Баг встречается в асинхронном режиме конфигурации

**Comment by artbear** [comment]
Выполнено.

**Comment by kwazispb** [comment]
баг все еще есть
ОШИБКА - Причина ошибки:Получен неожиданный/неверный результат работы - Не найден файл статуса D:\Git\Pr\build\xddExitCodePath.txt
Возможна, работа 1С:Предприятие завершилась некорректно.
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\vanessa-runner\src\Классы\МенеджерКонфигуратора.os / Ошибка в строке: 286 / Получен неожиданный/неверный результат работы - Не найден файл статуса D:\Git\Pr\build\xddExitCodePath.txt
Возможна, работа 1С:Предприятие завершилась некорректно.} 
использую версию установленную с помощью opm 6.6.5

**Comment by artbear** [comment]
@kwazispb у вас что-то не то с настройками запуска, скорее всего

смотри [спец.пункта FAQ](https://github.com/vanessa-opensource/add/blob/develop/F.A.Q.MD#1-%D0%BA%D0%B0%D0%BA-%D1%80%D0%B5%D1%88%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%BF%D1%80%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%BC-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%84%D0%B8%D1%87%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B5%D0%B2)

**Comment by kwazispb** [comment]
@artbear тем не менее, несмотря на ошибку тесты выполняются. На что она может повлиять?

**Comment by kwazispb** [comment]
в env.json была указана неверная версия платформы для клиент-серверной базы. База запускалась в итоге, но вот с этой ошибкой.

**Comment by khristovskii-mdxprt-omsk** [comment]
Здравствуйте. Столкнулся с такой же проблемой с отсутствием файла xddExitCodePath. Даже пробовал создавать вручную, указывал путь к нему в json, но при запуске xunit он удаляется и снова показывает ошибку. Не знаю что делать. База, логин, пароль, версия платформы указаны верно, по правилам составления json.

**Comment by skirdinsa** [comment]
> Здравствуйте. Столкнулся с такой же проблемой с отсутствием файла xddExitCodePath. Даже пробовал создавать вручную, указывал путь к нему в json, но при запуске xunit он удаляется и снова показывает ошибку. Не знаю что делать. База, логин, пароль, версия платформы указаны верно, по правилам составления json.

Столкнулся с аналогичной проблемой, помогло указание конкретной версии 1с в vrunner.json
	"--v8version": "8.3.22",

**Comment by kjhkhjkhj** [comment]
Добрый день.
Тоже столкнулся с проблемой как у @khristovskii-mdxprt-omsk. Проверял базу, логин, пароль, указал конкретную версию 1с в vrunner.json "--v8version": "8.3.24.1667". Ошибка все равно присутствует. Подскажите, пожалуйста, как исправить?

**Comment by xenus206** [comment]
Поделюсь решением - "ОШИБКА - Получен неожиданный/неверный результат работы - Не найден файл статуса", 
Боролся долго, оказалось, что менеджер просто не успевал дождаться, пока клиент запустится и будет готов принять соединение.
Решение в таймауте в функции ТаймаутВСекундах() в обработке add/plugins/ТестКлиенты.epf, увеличил со 120 до 300 и ошибка ушла.
Может сделать это параметром?
