### ISSUE TITLE
Вывод времени выполнения шагов/сценариев/фич

### ISSUE THREAD

**Issue by KrapivinAndrey** [vanessa-opensource/add#732]
**Существует проблема**
Сложно оценить сколько выполняется тест и где самое тонкое место

**Хотелось бы иметь следующую функциональность**
![image](https://user-images.githubusercontent.com/586025/81174261-f5dfdf00-8fba-11ea-8205-840d2f6c649c.png)

**Дополнительный контекст**

**Comment by KrapivinAndrey** [comment]
Еще идея: пара шагов НачатьЗамер и ЗакончитьЗамер - для вывода в лог времени операции. Иногда нужна такая информация

**Comment by artbear** [comment]
да, шаги были бы полезны

**Comment by artbear** [comment]
выполнено в https://github.com/vanessa-opensource/add/pull/761
