### ISSUE TITLE
Необходимо загружать макеты в формате JSON

### ISSUE THREAD

**Issue by yukon39** [vanessa-opensource/add#733]
**Существует проблема**
При указании шага `Я загружаю макет "fixtures/fixture.json"` макеты в формате JSON не загружаются.

**Хотелось бы иметь следующую функциональность**
Хотелось бы иметь возможность загрузки макетов в текстовом формате JSON, а не только в двоичном MXL.

**Дополнительный контекст**
Сериализатор XML поддерживает выгрузку и частично загрузку данных из формата JSON.

**Comment by yukon39** [comment]
Также существует проблема, что Сериализатор не загружает из формата JSON табличные части: https://github.com/vanessa-opensource/add/issues/484

**Comment by artbear** [comment]
Выполнено в https://github.com/vanessa-opensource/add/pull/766
